### ISSUE TITLE
Could not find nessus_rest-0.1.4 in any of the sources

### ISSUE THREAD

**Issue by hktalent** [guillomovitch/Net-Nessus-REST#10]
bundle install
Fetching gem metadata from https://ruby.taobao.org/............
Fetching version metadata from https://ruby.taobao.org/..
Resolving dependencies....
Could not find nessus_rest-0.1.4 in any of the sources

mac os 10.11.6

**Comment by digglife** [comment]
Dude, this is a **Perl** module, not a Ruby gem ... :sweat:

**Comment by hktalent** [comment]
thanks ，i found：
wget https://rubygems.org/gems/rake-11.2.2.gem
wget https://rubygems.org/gems/i18n-0.7.0.gem
wget https://rubygems.org/gems/json-1.8.3.gem
wget https://rubygems.org/gems/minitest-5.9.0.gem
wget https://rubygems.org/gems/thread_safe-0.3.5.gem
wget https://rubygems.org/gems/builder-3.2.2.gem
wget https://rubygems.org/gems/erubis-2.7.0.gem
wget https://rubygems.org/gems/mini_portile2-2.1.0.gem
wget https://rubygems.org/gems/pkg-config-1.1.7.gem
wget https://rubygems.org/gems/rack-1.6.4.gem
wget https://rubygems.org/gems/arel-6.0.3.gem
wget https://rubygems.org/gems/addressable-2.4.0.gem
wget https://rubygems.org/gems/ffi-1.9.14.gem
wget https://rubygems.org/gems/contracts-0.14.0.gem
wget https://rubygems.org/gems/gherkin-4.0.0.gem
wget https://rubygems.org/gems/cucumber-wire-0.0.1.gem
wget https://rubygems.org/gems/diff-lcs-1.2.5.gem
wget https://rubygems.org/gems/multi_json-1.12.1.gem
wget https://rubygems.org/gems/multi_test-0.1.2.gem
wget https://rubygems.org/gems/rspec-support-3.5.0.gem
wget https://rubygems.org/gems/thor-0.19.1.gem
wget https://rubygems.org/gems/bcrypt-3.1.11.gem
wget https://rubygems.org/gems/bit-struct-0.15.0.gem
wget https://rubygems.org/gems/mime-types-data-3.2016.0521.gem
wget https://rubygems.org/gems/coderay-1.1.1.gem
wget https://rubygems.org/gems/docile-1.1.5.gem
wget https://rubygems.org/gems/multipart-post-2.0.0.gem
wget https://rubygems.org/gems/filesize-0.1.1.gem
wget https://rubygems.org/gems/fivemat-1.3.2.gem
wget https://rubygems.org/gems/rkelly-remix-0.0.6.gem
wget https://rubygems.org/gems/metasm-1.0.2.gem
wget https://rubygems.org/gems/pg-0.18.4.gem
wget https://rubygems.org/gems/pg_array_parser-0.0.9.gem
wget https://rubygems.org/gems/rubyntlm-0.6.0.gem
wget https://rubygems.org/gems/rubyzip-1.2.0.gem
wget https://rubygems.org/gems/metasploit-payloads-1.1.13.gem
wget https://rubygems.org/gems/metasploit_payloads-mettle-0.0.6.gem
wget https://rubygems.org/gems/msgpack-1.0.0.gem
wget https://rubygems.org/gems/nessus_rest-0.1.4.gem
wget https://rubygems.org/gems/net-ssh-3.2.0.gem
wget https://rubygems.org/gems/network_interface-0.0.1.gem
wget https://rubygems.org/gems/openssl-ccm-1.2.1.gem
wget https://rubygems.org/gems/openvas-omp-0.0.4.gem
wget https://rubygems.org/gems/pcaprub-0.12.4.gem
wget https://rubygems.org/gems/patch_finder-1.0.2.gem
wget https://rubygems.org/gems/rb-readline-r7-0.5.2.0.gem
wget https://rubygems.org/gems/redcarpet-3.3.4.gem
wget https://rubygems.org/gems/rex-text-0.2.1.gem
wget https://rubygems.org/gems/rex-java-0.1.2.gem
wget https://rubygems.org/gems/rex-registry-0.1.0.gem
wget https://rubygems.org/gems/rex-struct2-0.1.0.gem
wget https://rubygems.org/gems/robots-0.10.1.gem
wget https://rubygems.org/gems/sqlite3-1.3.11.gem
wget https://rubygems.org/gems/sshkey-1.8.0.gem
wget https://rubygems.org/gems/windows_error-0.0.2.gem
wget https://rubygems.org/gems/method_source-0.8.2.gem
wget https://rubygems.org/gems/slop-3.6.0.gem
wget https://rubygems.org/gems/simplecov-html-0.10.0.gem
wget https://rubygems.org/gems/timecop-0.8.1.gem
wget https://rubygems.org/gems/yard-0.9.5.gem
wget https://rubygems.org/gems/bundler-1.12.5.gem
wget https://rubygems.org/gems/tzinfo-1.2.2.gem
wget https://rubygems.org/gems/nokogiri-1.6.8.gem
wget https://rubygems.org/gems/rack-test-0.6.3.gem
wget https://rubygems.org/gems/childprocess-0.5.9.gem
wget https://rubygems.org/gems/cucumber-core-1.5.0.gem
wget https://rubygems.org/gems/rspec-expectations-3.5.0.gem
wget https://rubygems.org/gems/rspec-core-3.5.2.gem
wget https://rubygems.org/gems/rspec-mocks-3.5.0.gem
wget https://rubygems.org/gems/mime-types-3.1.gem
wget https://rubygems.org/gems/faraday-0.9.2.gem
wget https://rubygems.org/gems/jsobfu-0.4.1.gem
wget https://rubygems.org/gems/packetfu-1.1.11.gem
wget https://rubygems.org/gems/rex-arch-0.1.1.gem
wget https://rubygems.org/gems/rex-mime-0.1.1.gem
wget https://rubygems.org/gems/rex-ole-0.1.2.gem
wget https://rubygems.org/gems/rex-random_identifier-0.1.0.gem
wget https://rubygems.org/gems/rex-zip-0.1.0.gem
wget https://rubygems.org/gems/pry-0.10.4.gem
wget https://rubygems.org/gems/simplecov-0.12.0.gem
wget https://rubygems.org/gems/activesupport-4.2.7.1.gem
wget https://rubygems.org/gems/tzinfo-data-1.2016.6.gem
wget https://rubygems.org/gems/loofah-2.0.3.gem
wget https://rubygems.org/gems/xpath-2.0.0.gem
wget https://rubygems.org/gems/recog-2.0.22.gem
wget https://rubygems.org/gems/cucumber-2.4.0.gem
wget https://rubygems.org/gems/sawyer-0.7.0.gem
wget https://rubygems.org/gems/rex-powershell-0.1.64.gem
wget https://rubygems.org/gems/rails-deprecated_sanitizer-1.0.3.gem
wget https://rubygems.org/gems/activemodel-4.2.7.1.gem
wget https://rubygems.org/gems/factory_girl-4.7.0.gem
wget https://rubygems.org/gems/shoulda-matchers-3.1.1.gem
wget https://rubygems.org/gems/rails-html-sanitizer-1.0.3.gem
wget https://rubygems.org/gems/capybara-2.7.1.gem
wget https://rubygems.org/gems/aruba-0.14.1.gem
wget https://rubygems.org/gems/octokit-4.3.0.gem
wget https://rubygems.org/gems/rails-dom-testing-1.0.7.gem
wget https://rubygems.org/gems/activerecord-4.2.7.1.gem
wget https://rubygems.org/gems/actionview-4.2.7.1.gem
wget https://rubygems.org/gems/arel-helpers-2.3.0.gem
wget https://rubygems.org/gems/postgres_ext-3.0.0.gem
wget https://rubygems.org/gems/actionpack-4.2.7.1.gem
wget https://rubygems.org/gems/railties-4.2.7.1.gem
wget https://rubygems.org/gems/cucumber-rails-1.4.4.gem
wget https://rubygems.org/gems/factory_girl_rails-4.7.0.gem
wget https://rubygems.org/gems/metasploit-concern-2.0.1.gem
wget https://rubygems.org/gems/metasploit-model-2.0.0.gem
wget https://rubygems.org/gems/rspec-rails-3.5.1.gem
wget https://rubygems.org/gems/metasploit_data_models-2.0.0.gem
wget https://rubygems.org/gems/metasploit-credential-2.0.3.gem
wget https://rubygems.org/gems/metasploit-framework-4.12.24
